pipelines:
  branches:
    master:
      - step:
          name: Build staging environment
          image: node:8
          caches:
            - node
          script:
            - yarn
            - yarn test
            - yarn deploy
    develop:
      - step:
          name: Build staging environment
          image: node:8
          caches:
            - node
          script:
            - yarn
            - yarn test
            - yarn deploy-prod
