pipelines:
  branches:
    master:
      - step:
          name: Build staging environment
          image: teracy/angular-cli
          caches:
            - node
          script:
            - npm install
            - ng lint
            - ng build --env staging
            - npm install -g aerobatic-cli
            - aero deploy --directory build
