image: node:8
pipelines:
  branches:
    staging:
      - step:
          name: Build staging environment
          image: teracy/angular-cli
          deployment: staging
          caches:
            - yarncustom
            - globalnode
          script:
            - yarn
            - ng lint
            - ng build --aot --prod
            - npm install -g aerobatic-cli
            - aero deploy -s staging
    master:
      - step:
          name: Build and deploy to production
          image: node:8
          caches:
            - node
          script:
            - yarn
            - yarn test
            - yarn deploy-prod
    develop:
      - step:
          name: Build and deploy to development
          image: node:8
          caches:
            - node
          script:
            - yarn
            - yarn test
            - yarn deploy
