image: node:8
pipelines:
  branches:
    master:
      - step:
          script:
            - node -v
      - step:
          name: Build staging environment
          image: teracy/angular-cli
          caches:
            - yarncustom
            - globalnode
          script:
            - yarn
            - ng lint
            - ng build --aot --prod
            - npm install -g aerobatic-cli
            - aero deploy
definitions:
  caches:
    globalnode: /usr/local/lib/node_modules
    yarncustom: /usr/local/share/.cache/yarn/v1
