image: node:8
pipelines:
  branches:
    staging:
      - step:
          name: Build staging environment
          image: teracy/angular-cli
          deployment: staging
          caches:
            - yarncustom
            - globalnode
          script:
            - yarn
            - ng lint
            - ng build --aot --prod
            - npm install -g aerobatic-cli
            - aero deploy -s staging
    master:
      - step:
          script:
            - node -v
      - step:
          name: Build staging environment
          image: teracy/angular-cli
          deployment: test
          caches:
            - yarncustom
            - globalnode
          script:
            - yarn
            - ng lint
            - ng build --aot --prod
            - npm install -g aerobatic-cli
            - aero deploy -s test
    tags:
      v*:
        - step:
            name: Build staging environment
            image: teracy/angular-cli
            deployment: production
            caches:
              - yarncustom
              - globalnode
            script:
              - yarn
              - ng lint
              - ng build --aot --prod
              - npm install -g aerobatic-cli
              - aero deploy
definitions:
  caches:
    globalnode: /usr/local/lib/node_modules
    yarncustom: /usr/local/share/.cache/yarn/v1
