pipelines:
  branches:
    master:
      - step:
          name: Build staging environment
          image: teracy/angular-cli
          caches:
            - node
            - globalnode
          script:
            - npm install
            - ng lint
            - ng build --aot --prod
            - npm install -g aerobatic-cli
            - aero deploy
definitions:
  caches:
    globalnode: /usr/local/lib/node_modules
